{
 "title": "TQA Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Average request duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "1000 * rate(http_request_duration_seconds_sum{handler=\"/answer\", job=\"tqa\"}[1m]) / \nrate(http_request_duration_seconds_count{handler=\"/answer\", job=\"tqa\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{handler=\"/answer\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "1000*histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{handler=\"/answer\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000*histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{handler=\"/answer\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "1000*histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{handler=\"/answer\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}